### ISSUE TITLE
invalid paretheses closing

### ISSUE THREAD

**Issue by kuboon** [Beat-Nick/erb2slim#12]
I tested my html on erb2slim.com and got following result.

html:
`<p style="font-family: Arial,sans-serif; font-size: 14px;">hoge</p>
`
converted slim:
`p style=("font-family: Arial),sans-serif; font-size: 14px;"  hoge
`

**Comment by Beat-Nick** [comment]
This looks like a bug in haml2slim. The string gets converted into haml correctly from html2haml which outputs:

` "%p{:style => \"font-family: Arial,sans-serif; font-size: 14px;\"} hoge\n"`

Then when this string is passed into haml2slim it drops the final parentheses. I've tried a few different encodings besides UTF-8 with no luck. My best suggestion is to use the second option on the site which uses html2slim instead of a ticket since haml2slim repo hasn't been updated in years.
