### ISSUE TITLE
Dynamic class names conversion issue to slim

### ISSUE THREAD

**Issue by ziaulrehman40** [Beat-Nick/erb2slim#19]
```
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
```

Tried converting this to slim(the second option on site named `slim`, not the first one which is ambiguously named: `ERB -> Haml -> Slim`), and got invalid conversion which looked something like:

```
- flash.each do |key, value|
  |  <div class="
  = flash_class(key)
  | "> 
  = value
```

**Comment by Beat-Nick** [comment]
The first option takes the code and processes it into Haml before using Haml2slim library to produce the final code. This is the default option since these libraries seem to produce the most consistent results and what I suggest people use (especially since all the converters are no longer maintained it looks like).

Running the conversion with the first option seems to output valid code so I will be closing this ticket. You can also take a long shot and post conversion issue for html2slim.
